**LAB 4**

**TASK 1**

In [ ]:
import numpy as np

X = np.arange(2, 33, 2).reshape(4, 4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


**TASK 2**

In [ ]:
import numpy as np
X = np.arange(1, 26).reshape(5, 5)
Y = X[X % 2 != 0]

print("Original Array:\n", X)
print("\nOdd Numbers Array:\n", Y)

Original Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Odd Numbers Array:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25]


**TASK 3**

In [2]:
import numpy as np


X = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4))

print(X)


[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


**TASK 4**

In [3]:
import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)


# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)

(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[ 1.67245996  0.59054873  0.85814677 ... -1.15406867  0.76950144
  -1.25840046]
 [-1.1644893   0.20149042  0.47168967 ... -0.57154243  0.08097116
  -0.57763667]
 [-0.37864447  0.40423912 -1.54143269 ...  0.21194857  1.44310792
  -1.003028  ]
 ...
 [-0.21272036  1.24605719 -0.84368263 ... -1.4086693  -0.65436561
   1.01517161]
 [-0.13081739 -1.48146075 -1.78323428 ...  1.14752102 -0.60959419
   1.43436792]
 [-1.56270717  0.26313699 -1.41663187 ...  1.69677945 -1.57014481
   0.15681728]]
Average of all values in X_norm: 2.4158453015843405e-17
Average of minimum values in each column of X_norm: -1.7072729231099362
Average of maximum values in each column of X_norm: 1.7304797015286268
Random permutation of row indices: [989 327 184 666 436 195 644 898 446  56 843  34 273 715 645 554 921 484
 519   5 697  38 142 198 803 970 804 536  42 748 110 712 301 909   7 814
 250  40 818 605 858 840 828 612 956 274 432 296